language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install twine;
  - pip install -e .
  - if [[ $travis_python_version == '2.6' ]]; then
      pip install ordereddict
    fi
  - if [[ $travis_python_version == '2.7' ]]; then
      python setup.py sdist bdist_wheel;
    fi

script:
  - python -m dbtoolspy.tokenizer
  - python -m dbtoolspy.macro
  - python -m dbtoolspy.template tests/test.subs

after_success:
  - if [[ ! -z "$TRAVIS_TAG" && $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      echo [distutils]                > ~/.pypirc;
      echo index-servers = mypypi    >> ~/.pypirc;
      echo [mypypi]                  >> ~/.pypirc;
      echo repository=$PYPI_URL      >> ~/.pypirc;
      echo username=$PYPI_USER       >> ~/.pypirc;
      echo password=$PYPI_PASSWORD   >> ~/.pypirc;
      twine upload -r mypypi dist/dbtoolspy-*.tar.gz;
      twine upload -r mypypi dist/dbtoolspy-*.whl;
    fi
